version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Tambahkan build environment yang benar
build:
  jobs:
    post_create_environment:
      - python -m pip install --upgrade pip setuptools virtualenv

sphinx:
  configuration: docs/conf.py

# Tambahkan requirements jika diperlukan
python:
  install:
    - requirements: docs/requirements.txt