version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py
  # TAMBAHKAN LINE INI:
  builder: html
  fail_on_warning: false

# TAMBAHKAN BAGIAN INI:
formats:
  - pdf
  - epub

python:
  install:
    - requirements: docs/requirements.txt